name: Deploy to Netlify

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - ".nojekyll"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g html-minifier terser

      - name: Minify index.html
        run: |
          if [ -f index.html ]; then
            # 压缩 index.html 并直接替换原文件
            html-minifier --collapse-whitespace --remove-comments --remove-empty-attributes --minify-css true --minify-js true index.html > index.html.tmp && mv index.html.tmp index.html
          else
            echo "index.html not found, skipping compression."
          fi

      - name: Minify sw.js
        run: |
          if [ -f sw.js ]; then
            # 压缩 sw.js 并直接替换原文件
            terser sw.js -o sw.js.tmp --compress --mangle && mv sw.js.tmp sw.js
          else
            echo "sw.js not found, skipping compression."
          fi

      - name: Optimize Markdown Files
        run: |
          # 遍历所有 .md 文件并优化（删除注释和空行）
          for file in **/*.md; do
            if [ -f "$file" ]; then
              # 删除 Markdown 文件中的注释和空行
              sed -i '/^\s*<!--.*-->$/d' $file  # 删除注释
              sed -i '/^\s*$/d' $file  # 删除空行
              echo "Optimized $file"
            fi
          done

      - name: Install Netlify CLI
        run: npm install --global netlify-cli@latest

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=. --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: '3'
          keep_minimum_runs: '0'